<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__fluid-quad-image-label-v2_style_fluidL_00fc7b</name>
   <tag></tag>
   <elementGuidId>012b6d56-4b7f-406c-a282-fbe721b6c1d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a-section._fluid-quad-image-label-v2_style_gridRowTwo__15woW > div.a-section.a-spacing-none._fluid-quad-image-label-v2_style_quadrantContainer__3TMqG._fluid-quad-image-label-v2_style_rightQuadrant__PI01n > a.a-link-normal._fluid-quad-image-label-v2_style_centerImage__30wh-.aok-block.image-window > div.a-section.a-spacing-none._fluid-quad-image-label-v2_style_fluidImageContainer__2SOMr > img._fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK._fluid-quad-image-label-v2_style_fluidImage__gTBjA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstanceAkarEtP3Twn5vCFqy9tQvw']/div[2]/div[2]/div[2]/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>287246c5-cb44-4607-853c-5b2ecc0fd07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Chairs</value>
      <webElementGuid>bc6ca5fd-97f3-4149-b98b-50760b8fba08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Chair_2x._SY232_CB667159060_.jpg</value>
      <webElementGuid>4c6a4411-d2f7-4c64-86c8-352da11e33eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK _fluid-quad-image-label-v2_style_fluidImage__gTBjA</value>
      <webElementGuid>ccdff03d-1047-4925-b025-bdee1e7f936e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Chair_2x._SY232_CB667159060_.jpg</value>
      <webElementGuid>88848265-56ef-474f-9d7b-9d88c1df7e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstanceAkarEtP3Twn5vCFqy9tQvw&quot;)/div[@class=&quot;_fluid-quad-image-label-v2_style_fluidQuadImageLabelBody__3tld0&quot;]/div[@class=&quot;a-section _fluid-quad-image-label-v2_style_gridRowTwo__15woW&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-quad-image-label-v2_style_quadrantContainer__3TMqG _fluid-quad-image-label-v2_style_rightQuadrant__PI01n&quot;]/a[@class=&quot;a-link-normal _fluid-quad-image-label-v2_style_centerImage__30wh- aok-block image-window&quot;]/div[@class=&quot;a-section a-spacing-none _fluid-quad-image-label-v2_style_fluidImageContainer__2SOMr&quot;]/img[@class=&quot;_fluid-quad-image-label-v2_style_fluidLandscapeImage__2euAK _fluid-quad-image-label-v2_style_fluidImage__gTBjA&quot;]</value>
      <webElementGuid>13544871-7a95-4216-8838-56ae4339461c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstanceAkarEtP3Twn5vCFqy9tQvw']/div[2]/div[2]/div[2]/a/div/img</value>
      <webElementGuid>74ec1230-d8a9-4373-84ba-a6038394c5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Chairs']</value>
      <webElementGuid>88d51a46-c1b0-409f-900b-e7882e08d258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a/div/img</value>
      <webElementGuid>5f18978d-4c83-4e1c-bf23-22a663e2e509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Chairs' and @src = 'https://images-na.ssl-images-amazon.com/images/G/01/AmazonExports/Fuji/2021/June/Fuji_Quad_Chair_2x._SY232_CB667159060_.jpg']</value>
      <webElementGuid>1f57c3df-f7fe-4636-aa74-cabef19fbc01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
